"""Shared constants for gameplay, timing, layout, and colors."""

# Window and timing settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 700
FPS = 60

# Race states and timing
COUNTDOWN = "COUNTDOWN"
RACING = "RACING"
FINISHED = "FINISHED"
PROFILE_SETUP = "PROFILE_SETUP"
PROFILE_SCREEN = "PROFILE_SCREEN"
MAIN_MENU = "MAIN_MENU"
CAR_SELECTION = "CAR_SELECTION"
TRACK_SELECTION = "TRACK_SELECTION"
RACE_SCREEN = "RACE_SCREEN"
PAUSED = "PAUSED"
SETTINGS_SCREEN = "SETTINGS_SCREEN"
RACE_RESTARTED = "RACE_RESTARTED"
COUNTDOWN_DURATION = 3.0
GO_DISPLAY_DURATION = 0.8
START_LINE_DISTANCE = 200.0
POST_FINISH_DECELERATION = 90.0

# Road layout
ROAD_WIDTH = 510
ROAD_LEFT = (SCREEN_WIDTH - ROAD_WIDTH) // 2
ROAD_RIGHT = ROAD_LEFT + ROAD_WIDTH
ROAD_SHOULDER_WIDTH = 12
LANE_WIDTH = ROAD_WIDTH // 3
EDGE_LINE_WIDTH = 6
LANE_LINE_WIDTH = 5
DASH_HEIGHT = 42
DASH_GAP = 34
RELATIVE_MOTION_SCALE = 1.25
ROAD_SAMPLE_HEIGHT = 6
TRACK_CURVE_SAMPLE_DISTANCE = 80.0

# Shared player-car layout
PLAYER_BODY_WIDTH = 70
PLAYER_HEIGHT = 132
PLAYER_WHEEL_OVERHANG = 5
PLAYER_START_X = SCREEN_WIDTH / 2
PLAYER_Y = SCREEN_HEIGHT - 172

# Opponent car layout
OPPONENT_WIDTH = 62
OPPONENT_HEIGHT = 116

# Fair body-sized collision boxes exclude wheels and small decorations.
PLAYER_HITBOX_WIDTH = 56
PLAYER_HITBOX_HEIGHT = 118
OPPONENT_HITBOX_WIDTH = 50
OPPONENT_HITBOX_HEIGHT = 104
SHOW_HITBOXES = False
SHOW_AI_DEBUG = False
SHOW_TRACK_DEBUG = False

# Shared speed range; player performance values live in CarConfig.
MIN_SPEED = 0.0

# Shared nitro mechanics; capacity and performance live in CarConfig.
NITRO_DRAIN_RATE = 100.0 / 6.0
NITRO_RECHARGE_RATE = 100.0 / 25.0
NITRO_RECHARGE_DELAY = 1.25
NITRO_OVERSPEED_DECELERATION = 45.0

# Curved-track handling and off-road behavior
CURVE_FORCE_MULTIPLIER = 0.008
OFF_ROAD_TOLERANCE = 8.0
OFF_ROAD_OUTER_MARGIN = 40.0

# Shared competitive-AI tuning. Racer-specific values live in opponent.py.
AI_MIN_TARGET_FACTOR = 0.90
AI_MAX_TARGET_FACTOR = 1.00
AI_RACE_CONTEXT_DISTANCE = 350.0
AI_BEHIND_TARGET_BONUS = 0.012
AI_AHEAD_TARGET_PENALTY = 0.008
AI_CURVE_LOOKAHEAD_DISTANCE = 320.0
AI_CURVE_LOOKAHEAD_SAMPLES = 6
AI_CURVE_SPEED_REDUCTION_FACTOR = 145.0
AI_MAX_CURVE_SPEED_REDUCTION = 34.0
AI_MIN_CURVE_TARGET_SPEED = 130.0

# Arcade collision response
COLLISION_SPEED_RETENTION = 0.45
COLLISION_KNOCKBACK_DISTANCE = 58.0
COLLISION_COOLDOWN_DURATION = 1.25
CRASH_MESSAGE_DURATION = 0.8
PLAYER_FLASH_INTERVAL = 0.18

# Presentation effects do not alter world or collision coordinates.
COLLISION_SHAKE_DURATION = 0.20
COLLISION_SHAKE_AMPLITUDE = 6
FINISH_MESSAGE_DURATION = 1.25

# Start/finish line appearance
CHECKER_SIZE = 15
CHECKER_ROWS = 2

# Shared colors; terrain and shoulder colors are track-specific.
ROAD_COLOR = (47, 49, 53)
WHITE = (240, 240, 235)
BLACK = (18, 18, 20)
WINDOW_COLOR = (91, 145, 166)
WINDOW_HIGHLIGHT = (153, 199, 214)
CAR_FLASH_LIGHT = (255, 214, 214)
CAR_FLASH_OUTLINE = (255, 245, 245)
NITRO_BLUE = (44, 142, 255)
NITRO_CYAN = (137, 241, 255)
NITRO_METER_BACKGROUND = (31, 39, 48)
NITRO_METER_FILL = (54, 176, 232)
NITRO_METER_ACTIVE = (92, 232, 255)
